# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # AccountTerminationConfigurationResponse Model.
  class AccountTerminationConfigurationResponse < BaseModel
    # TODO: Write general description for this method
    # @return [AccountTerminationConfigurationPayload]
    attr_accessor :payload

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payload'] = 'payload'
      @_hash
    end

    def initialize(payload = nil)
      @payload = payload
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      if hash['payload']
        payload = AccountTerminationConfigurationPayload.from_hash(hash['payload'])
      end

      # Create object from extracted values.
      AccountTerminationConfigurationResponse.new(payload)
    end

    def self.from_element(root)
      payload = XmlUtilities.from_element(
        root, 'TerminationSettings',
        AccountTerminationConfigurationPayload
      )

      new(payload)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'TerminationSettings', payload)

      root
    end
  end
end
