# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Action.
  class ActionEnum
    ACTION_ENUM = [
      # TODO: Write general description for UNCHANGED
      UNCHANGED = 'UNCHANGED'.freeze,

      # TODO: Write general description for OFF
      OFF = 'OFF'.freeze,

      # TODO: Write general description for AS_SPECIFIED
      AS_SPECIFIED = 'AS_SPECIFIED'.freeze,

      # TODO: Write general description for INCORRECT_VALUE
      INCORRECT_VALUE = 'INCORRECT_VALUE'.freeze
    ].freeze
  end
end
