# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # BdrArchiveRetrievalResponse Model.
  class BdrArchiveRetrievalResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :info_message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['info_message'] = 'infoMessage'
      @_hash
    end

    def initialize(info_message = nil)
      @info_message = info_message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      info_message = hash['infoMessage']

      # Create object from extracted values.
      BdrArchiveRetrievalResponse.new(info_message)
    end

    def self.from_element(root)
      info_message = XmlUtilities.from_element(root, 'Info', String)

      new(info_message)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Info', info_message)

      root
    end
  end
end
