# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # EndpointType.
  class EndpointTypeEnum
    ENDPOINT_TYPE_ENUM = [
      # TODO: Write general description for TN
      TN = 'TN'.freeze,

      # TODO: Write general description for IPV4
      IPV4 = 'IPv4'.freeze,

      # TODO: Write general description for SIP
      SIP = 'SIP'.freeze,

      # TODO: Write general description for FQDN
      FQDN = 'FQDN'.freeze
    ].freeze
  end
end
