# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ImportTnError Model.
  class ImportTnError < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :phone_numbers

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :error_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phone_numbers'] = 'phoneNumbers'
      @_hash['code'] = 'code'
      @_hash['error_description'] = 'errorDescription'
      @_hash
    end

    def initialize(phone_numbers = nil,
                   code = nil,
                   error_description = nil)
      @phone_numbers = phone_numbers
      @code = code
      @error_description = error_description
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phone_numbers = hash['phoneNumbers']
      code = hash['code']
      error_description = hash['errorDescription']

      # Create object from extracted values.
      ImportTnError.new(phone_numbers,
                        code,
                        error_description)
    end

    def self.from_element(root)
      phone_numbers = XmlUtilities.from_element_to_array(
        root, 'TelephoneNumber', String,
        wrapping_element_name: 'TelephoneNumbers'
      )
      code = XmlUtilities.from_element(root, 'Code', Integer)
      error_description = XmlUtilities.from_element(root, 'Description', String)

      new(phone_numbers,
          code,
          error_description)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(
        doc, root, 'TelephoneNumber', phone_numbers,
        wrapping_element_name: 'TelephoneNumbers'
      )
      XmlUtilities.add_as_subelement(doc, root, 'Code', code)
      XmlUtilities.add_as_subelement(doc, root, 'Description',
                                     error_description)

      root
    end
  end
end
