# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ListingType.
  class ListingTypeEnum
    LISTING_TYPE_ENUM = [
      # TODO: Write general description for LISTED
      LISTED = 'LISTED'.freeze,

      # TODO: Write general description for NON_LISTED
      NON_LISTED = 'NON_LISTED'.freeze,

      # TODO: Write general description for NON_PUBLISHED
      NON_PUBLISHED = 'NON_PUBLISHED'.freeze
    ].freeze
  end
end
