# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # OrderStatus1.
  class OrderStatus1Enum
    ORDER_STATUS1_ENUM = [
      # TODO: Write general description for FOC
      FOC = 'FOC'.freeze,

      # TODO: Write general description for EXCEPTION
      EXCEPTION = 'EXCEPTION'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'PENDING'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for PARTIAL
      PARTIAL = 'PARTIAL'.freeze
    ].freeze
  end
end
