# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # PhoneNumber Model.
  class PhoneNumber < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number'] = 'number'
      @_hash
    end

    def initialize(number = nil)
      @number = number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number = hash['number']

      # Create object from extracted values.
      PhoneNumber.new(number)
    end

    def self.from_element(root)
      number = XmlUtilities.from_element(root, 'number', String)

      new(number)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'number', number)

      root
    end
  end
end
