# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # PortOutStatus1.
  class PortOutStatus1Enum
    PORT_OUT_STATUS1_ENUM = [
      # TODO: Write general description for NEW
      NEW = 'NEW'.freeze,

      # TODO: Write general description for SUPP
      SUPP = 'SUPP'.freeze,

      # TODO: Write general description for MODIFY
      MODIFY = 'MODIFY'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze,

      # TODO: Write general description for VALIDATION_FAILED_NEW
      VALIDATION_FAILED_NEW = 'VALIDATION_FAILED_NEW'.freeze,

      # TODO: Write general description for VALIDATION_FAILED_SUPP
      VALIDATION_FAILED_SUPP = 'VALIDATION_FAILED_SUPP'.freeze,

      # TODO: Write general description for VALIDATION_FAILED_MODIFY
      VALIDATION_FAILED_MODIFY = 'VALIDATION_FAILED_MODIFY'.freeze,

      # TODO: Write general description for EXCEPTION
      EXCEPTION = 'EXCEPTION'.freeze,

      # TODO: Write general description for SOA_PENDING
      SOA_PENDING = 'SOA_PENDING'.freeze,

      # TODO: Write general description for SOA_CONFLICT
      SOA_CONFLICT = 'SOA_CONFLICT'.freeze
    ].freeze
  end
end
