# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # PortCarrierType.
  class PortCarrierTypeEnum
    PORT_CARRIER_TYPE_ENUM = [
      # TODO: Write general description for WIRELESS
      WIRELESS = 'WIRELESS'.freeze,

      # TODO: Write general description for WIRELINE
      WIRELINE = 'WIRELINE'.freeze
    ].freeze
  end
end
