# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ProcessingStatus.
  class ProcessingStatusEnum
    PROCESSING_STATUS_ENUM = [
      # TODO: Write general description for PENDING
      PENDING = 'PENDING'.freeze,

      # TODO: Write general description for RECEIVED
      RECEIVED = 'RECEIVED'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'PROCESSING'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for PARTIAL
      PARTIAL = 'PARTIAL'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze
    ].freeze
  end
end
