# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ProcessingStatus5.
  class ProcessingStatus5Enum
    PROCESSING_STATUS5_ENUM = [
      # TODO: Write general description for RECEIVED
      RECEIVED = 'RECEIVED'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'PROCESSING'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for PARTIAL
      PARTIAL = 'PARTIAL'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze
    ].freeze
  end
end
