# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # RoutingExceptionType.
  class RoutingExceptionTypeEnum
    ROUTING_EXCEPTION_TYPE_ENUM = [
      # TODO: Write general description for BLOCK
      BLOCK = 'BLOCK'.freeze
    ].freeze
  end
end
