# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Supplemental.
  class SupplementalEnum
    SUPPLEMENTAL_ENUM = [
      # TODO: Write general description for NONE
      NONE = 'NONE'.freeze,

      # TODO: Write general description for CANCEL
      CANCEL = 'CANCEL'.freeze,

      # TODO: Write general description for UPDATE
      UPDATE = 'UPDATE'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze
    ].freeze
  end
end
