# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TnSipPeerResponse Model.
  class TnSipPeerResponse < BaseModel
    # TODO: Write general description for this method
    # @return [TnSipPeer]
    attr_accessor :payload

    # TODO: Write general description for this method
    # @return [AddressErrorDescription]
    attr_accessor :address_error_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payload'] = 'payload'
      @_hash['address_error_description'] = 'addressErrorDescription'
      @_hash
    end

    def initialize(payload = nil,
                   address_error_description = nil)
      @payload = payload
      @address_error_description = address_error_description
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payload = TnSipPeer.from_hash(hash['payload']) if hash['payload']
      if hash['addressErrorDescription']
        address_error_description = AddressErrorDescription.from_hash(hash['addressErrorDescription'])
      end

      # Create object from extracted values.
      TnSipPeerResponse.new(payload,
                            address_error_description)
    end

    def self.from_element(root)
      payload = XmlUtilities.from_element(root, 'SipPeer', TnSipPeer)
      address_error_description = XmlUtilities.from_element(
        root, 'AddressErrorDescription', AddressErrorDescription
      )

      new(payload,
          address_error_description)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'SipPeer', payload)
      XmlUtilities.add_as_subelement(doc, root, 'AddressErrorDescription',
                                     address_error_description)

      root
    end
  end
end
