# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Type1.
  class Type1Enum
    TYPE1_ENUM = [
      # TODO: Write general description for BLOCKED
      BLOCKED = 'BLOCKED'.freeze,

      # TODO: Write general description for CUSTOMER_API_VALIDATION
      CUSTOMER_API_VALIDATION = 'CUSTOMER_API_VALIDATION'.freeze
    ].freeze
  end
end
