# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # A2pState.
  class A2pStateEnum
    A2P_STATE_ENUM = [
      # TODO: Write general description for OFF
      OFF = 'OFF'.freeze,

      # TODO: Write general description for SYSTEM_DEFAULT
      SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'.freeze,

      # TODO: Write general description for OVERRIDDEN
      OVERRIDDEN = 'OVERRIDDEN'.freeze
    ].freeze
  end
end
