# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # AccountProduct Model.
  class AccountProduct < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_name'] = 'productName'
      @_hash
    end

    def initialize(product_name = nil)
      @product_name = product_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_name = hash['productName']

      # Create object from extracted values.
      AccountProduct.new(product_name)
    end

    def self.from_element(root)
      product_name = XmlUtilities.from_element(root, 'Name', String)

      new(product_name)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Name', product_name)

      root
    end
  end
end
