# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # AdminDataResponse Model.
  class AdminDataResponse < BaseModel
    # TODO: Write general description for this method
    # @return [ResponseStatus]
    attr_accessor :response_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['response_status'] = 'responseStatus'
      @_hash
    end

    def initialize(response_status = nil)
      @response_status = response_status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      response_status = ResponseStatus.from_hash(hash['responseStatus']) if
        hash['responseStatus']

      # Create object from extracted values.
      AdminDataResponse.new(response_status)
    end

    def self.from_element(root)
      response_status = XmlUtilities.from_element(root, 'ResponseStatus',
                                                  ResponseStatus)

      new(response_status)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'ResponseStatus',
                                     response_status)

      root
    end
  end
end
