# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ApplicationsSettings Model.
  class ApplicationsSettings < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :application

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['application'] = 'application'
      @_hash
    end

    def initialize(application = nil)
      @application = application
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      application = hash['application']

      # Create object from extracted values.
      ApplicationsSettings.new(application)
    end

    def self.from_element(root)
      application = XmlUtilities.from_element(root, 'HttpMessagingV2AppId',
                                              String)

      new(application)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'HttpMessagingV2AppId',
                                     application)

      root
    end
  end
end
