# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # AssociatedSipPeers Model.
  class AssociatedSipPeers < BaseModel
    # TODO: Write general description for this method
    # @return [List of AssociatedSipPeer]
    attr_accessor :associated_sip_peers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['associated_sip_peers'] = 'associatedSipPeers'
      @_hash
    end

    def initialize(associated_sip_peers = nil)
      @associated_sip_peers = associated_sip_peers
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      associated_sip_peers = nil
      unless hash['associatedSipPeers'].nil?
        associated_sip_peers = []
        hash['associatedSipPeers'].each do |structure|
          associated_sip_peers << (AssociatedSipPeer.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      AssociatedSipPeers.new(associated_sip_peers)
    end

    def self.from_element(root)
      associated_sip_peers = XmlUtilities.from_element_to_array(
        root, 'AssociatedSipPeer', AssociatedSipPeer
      )

      new(associated_sip_peers)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'AssociatedSipPeer',
                                           associated_sip_peers)

      root
    end
  end
end
