# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # AttributeProvisionType.
  class AttributeProvisionTypeEnum
    ATTRIBUTE_PROVISION_TYPE_ENUM = [
      # TODO: Write general description for ACCOUNT
      ACCOUNT = 'ACCOUNT'.freeze,

      # TODO: Write general description for ELEMENT
      ELEMENT = 'ELEMENT'.freeze,

      # TODO: Write general description for GATEWAY
      GATEWAY = 'GATEWAY'.freeze,

      # TODO: Write general description for MTAP
      MTAP = 'MTAP'.freeze,

      # TODO: Write general description for MTEP
      MTEP = 'MTEP'.freeze,

      # TODO: Write general description for MOAP
      MOAP = 'MOAP'.freeze,

      # TODO: Write general description for MOEP
      MOEP = 'MOEP'.freeze
    ].freeze
  end
end
