# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # BaseOrderType Model.
  class BaseOrderType < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :telephone_numbers

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :reservation_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :rate_center_abbreviation

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :npa

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :npa_nxx

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :toll_free_wild_card_pattern

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vanity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lata

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :npa_nxx_block

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :local_vanity

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :ends_in

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['telephone_numbers'] = 'telephoneNumbers'
      @_hash['reservation_ids'] = 'reservationIds'
      @_hash['rate_center_abbreviation'] = 'rateCenterAbbreviation'
      @_hash['state'] = 'state'
      @_hash['quantity'] = 'quantity'
      @_hash['npa'] = 'npa'
      @_hash['npa_nxx'] = 'npaNxx'
      @_hash['toll_free_wild_card_pattern'] = 'tollFreeWildCardPattern'
      @_hash['vanity'] = 'vanity'
      @_hash['lata'] = 'lata'
      @_hash['zip'] = 'zip'
      @_hash['city'] = 'city'
      @_hash['npa_nxx_block'] = 'npaNxxBlock'
      @_hash['local_vanity'] = 'localVanity'
      @_hash['ends_in'] = 'endsIn'
      @_hash
    end

    def initialize(telephone_numbers = nil,
                   reservation_ids = nil,
                   rate_center_abbreviation = nil,
                   state = nil,
                   quantity = nil,
                   npa = nil,
                   npa_nxx = nil,
                   toll_free_wild_card_pattern = nil,
                   vanity = nil,
                   lata = nil,
                   zip = nil,
                   city = nil,
                   npa_nxx_block = nil,
                   local_vanity = nil,
                   ends_in = nil)
      @telephone_numbers = telephone_numbers
      @reservation_ids = reservation_ids
      @rate_center_abbreviation = rate_center_abbreviation
      @state = state
      @quantity = quantity
      @npa = npa
      @npa_nxx = npa_nxx
      @toll_free_wild_card_pattern = toll_free_wild_card_pattern
      @vanity = vanity
      @lata = lata
      @zip = zip
      @city = city
      @npa_nxx_block = npa_nxx_block
      @local_vanity = local_vanity
      @ends_in = ends_in
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      telephone_numbers = hash['telephoneNumbers']
      reservation_ids = hash['reservationIds']
      rate_center_abbreviation = hash['rateCenterAbbreviation']
      state = hash['state']
      quantity = hash['quantity']
      npa = hash['npa']
      npa_nxx = hash['npaNxx']
      toll_free_wild_card_pattern = hash['tollFreeWildCardPattern']
      vanity = hash['vanity']
      lata = hash['lata']
      zip = hash['zip']
      city = hash['city']
      npa_nxx_block = hash['npaNxxBlock']
      local_vanity = hash['localVanity']
      ends_in = hash['endsIn']

      # Create object from extracted values.
      BaseOrderType.new(telephone_numbers,
                        reservation_ids,
                        rate_center_abbreviation,
                        state,
                        quantity,
                        npa,
                        npa_nxx,
                        toll_free_wild_card_pattern,
                        vanity,
                        lata,
                        zip,
                        city,
                        npa_nxx_block,
                        local_vanity,
                        ends_in)
    end

    def self.from_element(root)
      telephone_numbers = XmlUtilities.from_element_to_array(
        root, 'TelephoneNumber', String,
        wrapping_element_name: 'TelephoneNumberList'
      )
      reservation_ids = XmlUtilities.from_element_to_array(
        root, 'ReservationId', String,
        wrapping_element_name: 'ReservationIdList'
      )
      rate_center_abbreviation = XmlUtilities.from_element(root, 'RateCenter',
                                                           String)
      state = XmlUtilities.from_element(root, 'State', String)
      quantity = XmlUtilities.from_element(root, 'Quantity', Integer)
      npa = XmlUtilities.from_element(root, 'AreaCode', String)
      npa_nxx = XmlUtilities.from_element(root, 'NpaNxx', String)
      toll_free_wild_card_pattern = XmlUtilities.from_element(
        root, 'TollFreeWildCardPattern', String
      )
      vanity = XmlUtilities.from_element(root, 'TollFreeVanity', String)
      lata = XmlUtilities.from_element(root, 'LATA', String)
      zip = XmlUtilities.from_element(root, 'Zip', String)
      city = XmlUtilities.from_element(root, 'City', String)
      npa_nxx_block = XmlUtilities.from_element(root, 'NpaNxxX', String)
      local_vanity = XmlUtilities.from_element(root, 'LocalVanity', String)
      ends_in = XmlUtilities.from_element(root, 'EndsIn', TrueClass)

      new(telephone_numbers,
          reservation_ids,
          rate_center_abbreviation,
          state,
          quantity,
          npa,
          npa_nxx,
          toll_free_wild_card_pattern,
          vanity,
          lata,
          zip,
          city,
          npa_nxx_block,
          local_vanity,
          ends_in)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(
        doc, root, 'TelephoneNumber', telephone_numbers,
        wrapping_element_name: 'TelephoneNumberList'
      )
      XmlUtilities.add_array_as_subelement(
        doc, root, 'ReservationId', reservation_ids,
        wrapping_element_name: 'ReservationIdList'
      )
      XmlUtilities.add_as_subelement(doc, root, 'RateCenter',
                                     rate_center_abbreviation)
      XmlUtilities.add_as_subelement(doc, root, 'State', state)
      XmlUtilities.add_as_subelement(doc, root, 'Quantity', quantity)
      XmlUtilities.add_as_subelement(doc, root, 'AreaCode', npa)
      XmlUtilities.add_as_subelement(doc, root, 'NpaNxx', npa_nxx)
      XmlUtilities.add_as_subelement(doc, root, 'TollFreeWildCardPattern',
                                     toll_free_wild_card_pattern)
      XmlUtilities.add_as_subelement(doc, root, 'TollFreeVanity', vanity)
      XmlUtilities.add_as_subelement(doc, root, 'LATA', lata)
      XmlUtilities.add_as_subelement(doc, root, 'Zip', zip)
      XmlUtilities.add_as_subelement(doc, root, 'City', city)
      XmlUtilities.add_as_subelement(doc, root, 'NpaNxxX', npa_nxx_block)
      XmlUtilities.add_as_subelement(doc, root, 'LocalVanity', local_vanity)
      XmlUtilities.add_as_subelement(doc, root, 'EndsIn', ends_in)

      root
    end
  end
end
