# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # BulkTnList Model.
  class BulkTnList < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :tns

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tns'] = 'tns'
      @_hash
    end

    def initialize(tns = nil)
      @tns = tns
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      tns = hash['tns']

      # Create object from extracted values.
      BulkTnList.new(tns)
    end

    def self.from_element(root)
      tns = XmlUtilities.from_element_to_array(root, 'TN', String)

      new(tns)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'TN', tns)

      root
    end
  end
end
