# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # BulkPortinList Model.
  class BulkPortinList < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :portin_order_ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['portin_order_ids'] = 'portinOrderIds'
      @_hash
    end

    def initialize(portin_order_ids = nil)
      @portin_order_ids = portin_order_ids
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      portin_order_ids = hash['portinOrderIds']

      # Create object from extracted values.
      BulkPortinList.new(portin_order_ids)
    end

    def self.from_element(root)
      portin_order_ids = XmlUtilities.from_element_to_array(root,
                                                            'PortinOrderId',
                                                            String)

      new(portin_order_ids)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'PortinOrderId',
                                           portin_order_ids)

      root
    end
  end
end
