# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # CheckingMode.
  class CheckingModeEnum
    CHECKING_MODE_ENUM = [
      # TODO: Write general description for FALSE
      FALSE = 'FALSE'.freeze,

      # TODO: Write general description for TRUE
      TRUE = 'TRUE'.freeze,

      # TODO: Write general description for ONNETPORTABILITY
      ONNETPORTABILITY = 'ONNETPORTABILITY'.freeze,

      # TODO: Write general description for OFFNETPORTABILITY
      OFFNETPORTABILITY = 'OFFNETPORTABILITY'.freeze
    ].freeze
  end
end
