# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # CitySearchAndOrderType Model.
  class CitySearchAndOrderType < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['quantity'] = 'quantity'
      @_hash['city'] = 'city'
      @_hash['state'] = 'state'
      @_hash
    end

    def initialize(quantity = nil,
                   city = nil,
                   state = nil)
      @quantity = quantity
      @city = city
      @state = state
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      quantity = hash['quantity']
      city = hash['city']
      state = hash['state']

      # Create object from extracted values.
      CitySearchAndOrderType.new(quantity,
                                 city,
                                 state)
    end

    def self.from_element(root)
      quantity = XmlUtilities.from_element(root, 'Quantity', Integer)
      city = XmlUtilities.from_element(root, 'City', String)
      state = XmlUtilities.from_element(root, 'State', String)

      new(quantity,
          city,
          state)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Quantity', quantity)
      XmlUtilities.add_as_subelement(doc, root, 'City', city)
      XmlUtilities.add_as_subelement(doc, root, 'State', state)

      root
    end
  end
end
