# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # DeckType.
  class DeckTypeEnum
    DECK_TYPE_ENUM = [
      # TODO: Write general description for NPANXX
      NPANXX = 'NPANXX'.freeze,

      # TODO: Write general description for LATAOCN
      LATAOCN = 'LATAOCN'.freeze
    ].freeze
  end
end
