# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # DigestRequested.
  class DigestRequestedEnum
    DIGEST_REQUESTED_ENUM = [
      # TODO: Write general description for NONE
      NONE = 'none'.freeze,

      # TODO: Write general description for DAILY
      DAILY = 'daily'.freeze
    ].freeze
  end
end
