# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # DocumentType.
  class DocumentTypeEnum
    DOCUMENT_TYPE_ENUM = [
      # TODO: Write general description for LOA
      LOA = 'LOA'.freeze,

      # TODO: Write general description for INVOICE
      INVOICE = 'INVOICE'.freeze,

      # TODO: Write general description for CSR
      CSR = 'CSR'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze
    ].freeze
  end
end
