# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # EmergencyNotificationGroupsEndpointAssociationPayload Model.
  class EmergencyNotificationGroupsEndpointAssociationPayload < BaseModel
    # TODO: Write general description for this method
    # @return [List of EmergencyNotificationGroupEndpointAssociationPayload]
    attr_accessor :payload_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payload_list'] = 'payloadList'
      @_hash
    end

    def initialize(payload_list = nil)
      @payload_list = payload_list
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      payload_list = nil
      unless hash['payloadList'].nil?
        payload_list = []
        hash['payloadList'].each do |structure|
          payload_list << (EmergencyNotificationGroupEndpointAssociationPayload.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      EmergencyNotificationGroupsEndpointAssociationPayload.new(payload_list)
    end

    def self.from_element(root)
      payload_list = XmlUtilities.from_element_to_array(
        root, 'EmergencyNotificationEndpointOrder',
        EmergencyNotificationGroupEndpointAssociationPayload
      )

      new(payload_list)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root,
                                           'EmergencyNotificationEndpointOrder',
                                           payload_list)

      root
    end
  end
end
