# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # filetype.
  class FiletypeEnum
    FILETYPE_ENUM = [
      # TODO: Write general description for CSV
      CSV = 'CSV'.freeze,

      # TODO: Write general description for XLS
      XLS = 'XLS'.freeze
    ].freeze
  end
end
