# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # GeocodeRequestAddress Model.
  class GeocodeRequestAddress < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :house_prefix

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :house_no

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :house_suffix

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :pre_directional

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :street_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :street_suffix

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :post_directional

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_line2

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip4

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :county

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_type

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :reset_address_fields

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :latitude

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :longitude

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :addressline1

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['house_prefix'] = 'housePrefix'
      @_hash['house_no'] = 'houseNo'
      @_hash['house_suffix'] = 'houseSuffix'
      @_hash['pre_directional'] = 'preDirectional'
      @_hash['street_name'] = 'streetName'
      @_hash['street_suffix'] = 'streetSuffix'
      @_hash['post_directional'] = 'postDirectional'
      @_hash['address_line2'] = 'addressLine2'
      @_hash['city'] = 'city'
      @_hash['state_code'] = 'stateCode'
      @_hash['zip'] = 'zip'
      @_hash['zip4'] = 'zip4'
      @_hash['county'] = 'county'
      @_hash['country'] = 'country'
      @_hash['address_type'] = 'addressType'
      @_hash['reset_address_fields'] = 'resetAddressFields'
      @_hash['latitude'] = 'latitude'
      @_hash['longitude'] = 'longitude'
      @_hash['addressline1'] = 'addressline1'
      @_hash
    end

    def initialize(house_prefix = nil,
                   house_no = nil,
                   house_suffix = nil,
                   pre_directional = nil,
                   street_name = nil,
                   street_suffix = nil,
                   post_directional = nil,
                   address_line2 = nil,
                   city = nil,
                   state_code = nil,
                   zip = nil,
                   zip4 = nil,
                   county = nil,
                   country = nil,
                   address_type = nil,
                   reset_address_fields = nil,
                   latitude = nil,
                   longitude = nil,
                   addressline1 = nil)
      @house_prefix = house_prefix
      @house_no = house_no
      @house_suffix = house_suffix
      @pre_directional = pre_directional
      @street_name = street_name
      @street_suffix = street_suffix
      @post_directional = post_directional
      @address_line2 = address_line2
      @city = city
      @state_code = state_code
      @zip = zip
      @zip4 = zip4
      @county = county
      @country = country
      @address_type = address_type
      @reset_address_fields = reset_address_fields
      @latitude = latitude
      @longitude = longitude
      @addressline1 = addressline1
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      house_prefix = hash['housePrefix']
      house_no = hash['houseNo']
      house_suffix = hash['houseSuffix']
      pre_directional = hash['preDirectional']
      street_name = hash['streetName']
      street_suffix = hash['streetSuffix']
      post_directional = hash['postDirectional']
      address_line2 = hash['addressLine2']
      city = hash['city']
      state_code = hash['stateCode']
      zip = hash['zip']
      zip4 = hash['zip4']
      county = hash['county']
      country = hash['country']
      address_type = hash['addressType']
      reset_address_fields = hash['resetAddressFields']
      latitude = hash['latitude']
      longitude = hash['longitude']
      addressline1 = hash['addressline1']

      # Create object from extracted values.
      GeocodeRequestAddress.new(house_prefix,
                                house_no,
                                house_suffix,
                                pre_directional,
                                street_name,
                                street_suffix,
                                post_directional,
                                address_line2,
                                city,
                                state_code,
                                zip,
                                zip4,
                                county,
                                country,
                                address_type,
                                reset_address_fields,
                                latitude,
                                longitude,
                                addressline1)
    end

    def self.from_element(root)
      house_prefix = XmlUtilities.from_element(root, 'HousePrefix', String)
      house_no = XmlUtilities.from_element(root, 'HouseNumber', String)
      house_suffix = XmlUtilities.from_element(root, 'HouseSuffix', String)
      pre_directional = XmlUtilities.from_element(root, 'PreDirectional',
                                                  String)
      street_name = XmlUtilities.from_element(root, 'StreetName', String)
      street_suffix = XmlUtilities.from_element(root, 'StreetSuffix', String)
      post_directional = XmlUtilities.from_element(root, 'PostDirectional',
                                                   String)
      address_line2 = XmlUtilities.from_element(root, 'AddressLine2', String)
      city = XmlUtilities.from_element(root, 'City', String)
      state_code = XmlUtilities.from_element(root, 'StateCode', String)
      zip = XmlUtilities.from_element(root, 'Zip', String)
      zip4 = XmlUtilities.from_element(root, 'PlusFour', String)
      county = XmlUtilities.from_element(root, 'County', String)
      country = XmlUtilities.from_element(root, 'Country', String)
      address_type = XmlUtilities.from_element(root, 'AddressType', String)
      reset_address_fields = XmlUtilities.from_element(root,
                                                       'ResetAddressFields',
                                                       TrueClass)
      latitude = XmlUtilities.from_element(root, 'Latitude', String)
      longitude = XmlUtilities.from_element(root, 'Longitude', String)
      addressline1 = XmlUtilities.from_element(root, 'AddressLine1', String)

      new(house_prefix,
          house_no,
          house_suffix,
          pre_directional,
          street_name,
          street_suffix,
          post_directional,
          address_line2,
          city,
          state_code,
          zip,
          zip4,
          county,
          country,
          address_type,
          reset_address_fields,
          latitude,
          longitude,
          addressline1)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'HousePrefix', house_prefix)
      XmlUtilities.add_as_subelement(doc, root, 'HouseNumber', house_no)
      XmlUtilities.add_as_subelement(doc, root, 'HouseSuffix', house_suffix)
      XmlUtilities.add_as_subelement(doc, root, 'PreDirectional',
                                     pre_directional)
      XmlUtilities.add_as_subelement(doc, root, 'StreetName', street_name)
      XmlUtilities.add_as_subelement(doc, root, 'StreetSuffix', street_suffix)
      XmlUtilities.add_as_subelement(doc, root, 'PostDirectional',
                                     post_directional)
      XmlUtilities.add_as_subelement(doc, root, 'AddressLine2', address_line2)
      XmlUtilities.add_as_subelement(doc, root, 'City', city)
      XmlUtilities.add_as_subelement(doc, root, 'StateCode', state_code)
      XmlUtilities.add_as_subelement(doc, root, 'Zip', zip)
      XmlUtilities.add_as_subelement(doc, root, 'PlusFour', zip4)
      XmlUtilities.add_as_subelement(doc, root, 'County', county)
      XmlUtilities.add_as_subelement(doc, root, 'Country', country)
      XmlUtilities.add_as_subelement(doc, root, 'AddressType', address_type)
      XmlUtilities.add_as_subelement(doc, root, 'ResetAddressFields',
                                     reset_address_fields)
      XmlUtilities.add_as_subelement(doc, root, 'Latitude', latitude)
      XmlUtilities.add_as_subelement(doc, root, 'Longitude', longitude)
      XmlUtilities.add_as_subelement(doc, root, 'AddressLine1', addressline1)

      root
    end
  end
end
