# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # MessagingRoutes Model.
  class MessagingRoutes < BaseModel
    # TODO: Write general description for this method
    # @return [List of MessagingRoute]
    attr_accessor :routes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['routes'] = 'routes'
      @_hash
    end

    def initialize(routes = nil)
      @routes = routes
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      routes = nil
      unless hash['routes'].nil?
        routes = []
        hash['routes'].each do |structure|
          routes << (MessagingRoute.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      MessagingRoutes.new(routes)
    end

    def self.from_element(root)
      routes = XmlUtilities.from_element_to_array(root, 'MessagingRoute',
                                                  MessagingRoute)

      new(routes)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'MessagingRoute', routes)

      root
    end
  end
end
