# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # MmsSettings Model.
  class MmsSettings < BaseModel
    # TODO: Write general description for this method
    # @return [Protocol1Enum]
    attr_accessor :protocol

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['protocol'] = 'protocol'
      @_hash
    end

    def initialize(protocol = nil)
      @protocol = protocol
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      protocol = hash['protocol']

      # Create object from extracted values.
      MmsSettings.new(protocol)
    end

    def self.from_element(root)
      protocol = XmlUtilities.from_element(root, 'Protocol', String)

      new(protocol)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Protocol', protocol)

      root
    end
  end
end
