# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # MmsMM4TermHosts Model.
  class MmsMM4TermHosts < BaseModel
    # TODO: Write general description for this method
    # @return [List of MmsMM4TermHost]
    attr_accessor :hosts

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['hosts'] = 'hosts'
      @_hash
    end

    def initialize(hosts = nil)
      @hosts = hosts
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      hosts = nil
      unless hash['hosts'].nil?
        hosts = []
        hash['hosts'].each do |structure|
          hosts << (MmsMM4TermHost.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      MmsMM4TermHosts.new(hosts)
    end

    def self.from_element(root)
      hosts = XmlUtilities.from_element_to_array(
        root, 'TermHost', MmsMM4TermHost,
        wrapping_element_name: 'TermHosts'
      )

      new(hosts)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'TermHost', hosts,
                                           wrapping_element_name: 'TermHosts')

      root
    end
  end
end
