# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # MmsMM4OrigHost Model.
  class MmsMM4OrigHost < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :host_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :port

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :host_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :priority

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['host_name'] = 'hostName'
      @_hash['port'] = 'port'
      @_hash['host_id'] = 'hostId'
      @_hash['priority'] = 'priority'
      @_hash
    end

    def initialize(host_name = nil,
                   port = nil,
                   host_id = nil,
                   priority = nil)
      @host_name = host_name
      @port = port
      @host_id = host_id
      @priority = priority
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      host_name = hash['hostName']
      port = hash['port']
      host_id = hash['hostId']
      priority = hash['priority']

      # Create object from extracted values.
      MmsMM4OrigHost.new(host_name,
                         port,
                         host_id,
                         priority)
    end

    def self.from_element(root)
      host_name = XmlUtilities.from_element(root, 'HostName', String)
      port = XmlUtilities.from_element(root, 'Port', String)
      host_id = XmlUtilities.from_element(root, 'HostId', Integer)
      priority = XmlUtilities.from_element(root, 'Priority', Integer)

      new(host_name,
          port,
          host_id,
          priority)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'HostName', host_name)
      XmlUtilities.add_as_subelement(doc, root, 'Port', port)
      XmlUtilities.add_as_subelement(doc, root, 'HostId', host_id)
      XmlUtilities.add_as_subelement(doc, root, 'Priority', priority)

      root
    end
  end
end
