# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Operation.
  class OperationEnum
    OPERATION_ENUM = [
      # TODO: Write general description for ADD
      ADD = 'ADD'.freeze,

      # TODO: Write general description for REMOVE
      REMOVE = 'REMOVE'.freeze
    ].freeze
  end
end
