# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # OrderType.
  class OrderTypeEnum
    ORDER_TYPE_ENUM = [
      # TODO: Write general description for BULK_PORT_IN
      BULK_PORT_IN = 'bulk_port_in'.freeze,

      # TODO: Write general description for PORT_IN
      PORT_IN = 'port_in'.freeze,

      # TODO: Write general description for PORT_OUT
      PORT_OUT = 'port_out'.freeze,

      # TODO: Write general description for NEW_NUMBER
      NEW_NUMBER = 'new_number'.freeze,

      # TODO: Write general description for DISCONNECT
      DISCONNECT = 'disconnect'.freeze,

      # TODO: Write general description for IMPORT_TO_ACCOUNT
      IMPORT_TO_ACCOUNT = 'import_to_account'.freeze,

      # TODO: Write general description for LIDB
      LIDB = 'lidb'.freeze,

      # TODO: Write general description for DLDA
      DLDA = 'dlda'.freeze,

      # TODO: Write general description for LSR
      LSR = 'lsr'.freeze,

      # TODO: Write general description for E911
      E911 = 'e911'.freeze,

      # TODO: Write general description for TN_OPTION
      TN_OPTION = 'tn_option'.freeze,

      # TODO: Write general description for EXTERNAL_TNS
      EXTERNAL_TNS = 'external_tns'.freeze,

      # TODO: Write general description for NUMBERS_ASSIGNMENT
      NUMBERS_ASSIGNMENT = 'numbers_assignment'.freeze,

      # TODO: Write general description for IMPORT_TN_ORDERS
      IMPORT_TN_ORDERS = 'import_tn_orders'.freeze,

      # TODO: Write general description for REMOVE_IMPORTED_TN_ORDERS
      REMOVE_IMPORTED_TN_ORDERS = 'remove_imported_tn_orders'.freeze,

      # TODO: Write general description for CSR
      CSR = 'csr'.freeze,

      # TODO: Write general description for EMERGENCY_NOTIFICATION_GROUP
      EMERGENCY_NOTIFICATION_GROUP = 'emergency_notification_group'.freeze,

      # TODO: Write general description for EMERGENCY_ENDPOINT_GROUP
      EMERGENCY_ENDPOINT_GROUP = 'emergency_endpoint_group'.freeze
    ].freeze
  end
end
