# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ProcessingStatus4.
  class ProcessingStatus4Enum
    PROCESSING_STATUS4_ENUM = [
      # TODO: Write general description for DRAFT
      DRAFT = 'DRAFT'.freeze,

      # TODO: Write general description for PENDING_DOCUMENTS
      PENDING_DOCUMENTS = 'PENDING_DOCUMENTS'.freeze,

      # TODO: Write general description for SUBMITTED
      SUBMITTED = 'SUBMITTED'.freeze,

      # TODO: Write general description for REQUESTED_SUPP
      REQUESTED_SUPP = 'REQUESTED_SUPP'.freeze,

      # TODO: Write general description for FOC
      FOC = 'FOC'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for EXCEPTION
      EXCEPTION = 'EXCEPTION'.freeze,

      # TODO: Write general description for SNAPBACK
      SNAPBACK = 'SNAPBACK'.freeze,

      # TODO: Write general description for REQUESTED_CANCEL
      REQUESTED_CANCEL = 'REQUESTED_CANCEL'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze
    ].freeze
  end
end
