# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Products Model.
  class Products < BaseModel
    # TODO: Write general description for this method
    # @return [List of Product]
    attr_accessor :products

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['products'] = 'products'
      @_hash
    end

    def initialize(products = nil)
      @products = products
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      products = nil
      unless hash['products'].nil?
        products = []
        hash['products'].each do |structure|
          products << (Product.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Products.new(products)
    end

    def self.from_element(root)
      products = XmlUtilities.from_element_to_array(root, 'Product', Product)

      new(products)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'Product', products)

      root
    end
  end
end
