# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Protocol1.
  class Protocol1Enum
    PROTOCOL1_ENUM = [
      # TODO: Write general description for MM4
      MM4 = 'MM4'.freeze,

      # TODO: Write general description for HTTP
      HTTP = 'HTTP'.freeze
    ].freeze
  end
end
