# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Protocol.
  class ProtocolEnum
    PROTOCOL_ENUM = [
      # TODO: Write general description for SIP
      SIP = 'SIP'.freeze,

      # TODO: Write general description for SMPP
      SMPP = 'SMPP'.freeze,

      # TODO: Write general description for HTTP
      HTTP = 'HTTP'.freeze
    ].freeze
  end
end
