# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ProxyPeerValue Model.
  class ProxyPeerValue < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [ServiceTypeEnum]
    attr_accessor :service_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :proxy_peer_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['service_type'] = 'serviceType'
      @_hash['proxy_peer_id'] = 'proxyPeerId'
      @_hash
    end

    def initialize(name = nil,
                   service_type = nil,
                   proxy_peer_id = nil)
      @name = name
      @service_type = service_type
      @proxy_peer_id = proxy_peer_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      service_type = hash['serviceType']
      proxy_peer_id = hash['proxyPeerId']

      # Create object from extracted values.
      ProxyPeerValue.new(name,
                         service_type,
                         proxy_peer_id)
    end

    def self.from_element(root)
      name = XmlUtilities.from_element(root, 'Name', String)
      service_type = XmlUtilities.from_element(root, 'Service', String)
      proxy_peer_id = XmlUtilities.from_element(root, 'ProxyPeerId', Integer)

      new(name,
          service_type,
          proxy_peer_id)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Name', name)
      XmlUtilities.add_as_subelement(doc, root, 'Service', service_type)
      XmlUtilities.add_as_subelement(doc, root, 'ProxyPeerId', proxy_peer_id)

      root
    end
  end
end
