# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Reports Model.
  class Reports < BaseModel
    # TODO: Write general description for this method
    # @return [List of Report]
    attr_accessor :reports

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['reports'] = 'Reports'
      @_hash
    end

    def initialize(reports = nil)
      @reports = reports
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      reports = nil
      unless hash['Reports'].nil?
        reports = []
        hash['Reports'].each do |structure|
          reports << (Report.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Reports.new(reports)
    end

    def self.from_element(root)
      reports = XmlUtilities.from_element_to_array(root, 'Report', Report)

      new(reports)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'Report', reports)

      root
    end
  end
end
