# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ReportInstancesResponse Model.
  class ReportInstancesResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :report_instances

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['report_instances'] = 'reportInstances'
      @_hash
    end

    def initialize(report_instances = nil)
      @report_instances = report_instances
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      report_instances = hash['reportInstances']

      # Create object from extracted values.
      ReportInstancesResponse.new(report_instances)
    end

    def self.from_element(root)
      report_instances = XmlUtilities.from_element(root, 'Instances', String)

      new(report_instances)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Instances', report_instances)

      root
    end
  end
end
