# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ReportInstanceErrorDetails Model.
  class ReportInstanceErrorDetails < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['message'] = 'message'
      @_hash
    end

    def initialize(code = nil,
                   message = nil)
      @code = code
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash['code']
      message = hash['message']

      # Create object from extracted values.
      ReportInstanceErrorDetails.new(code,
                                     message)
    end

    def self.from_element(root)
      code = XmlUtilities.from_element(root, 'Code', Integer)
      message = XmlUtilities.from_element(root, 'Message', String)

      new(code,
          message)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Code', code)
      XmlUtilities.add_as_subelement(doc, root, 'Message', message)

      root
    end
  end
end
