# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Reservations Model.
  class Reservations < BaseModel
    # TODO: Write general description for this method
    # @return [List of Reservation]
    attr_accessor :reservations

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :count

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['reservations'] = 'reservations'
      @_hash['count'] = 'count'
      @_hash
    end

    def initialize(reservations = nil,
                   count = nil)
      @reservations = reservations
      @count = count
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      reservations = nil
      unless hash['reservations'].nil?
        reservations = []
        hash['reservations'].each do |structure|
          reservations << (Reservation.from_hash(structure) if structure)
        end
      end
      count = hash['count']

      # Create object from extracted values.
      Reservations.new(reservations,
                       count)
    end

    def self.from_element(root)
      reservations = XmlUtilities.from_element_to_array(root, 'Reservation',
                                                        Reservation)
      count = XmlUtilities.from_element(root, 'Count', Integer)

      new(reservations,
          count)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'Reservation',
                                           reservations)
      XmlUtilities.add_as_subelement(doc, root, 'Count', count)

      root
    end
  end
end
