# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # RogerUsedForTerminationSettings.
  class RogerUsedForTerminationSettingsEnum
    ROGER_USED_FOR_TERMINATION_SETTINGS_ENUM = [
      # TODO: Write general description for ENUM_FALSE
      ENUM_FALSE = 'false'.freeze,

      # TODO: Write general description for TRANSITION
      TRANSITION = 'transition'.freeze,

      # TODO: Write general description for ENUM_TRUE
      ENUM_TRUE = 'true'.freeze
    ].freeze
  end
end
