# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # RogerTerminationConfigurationPayload Model.
  class RogerTerminationConfigurationPayload < BaseModel
    # TODO: Write general description for this method
    # @return [Long]
    attr_accessor :termination_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :subnet_addressing_allowed

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['termination_id'] = 'terminationId'
      @_hash['subnet_addressing_allowed'] = 'subnetAddressingAllowed'
      @_hash
    end

    def initialize(termination_id = nil,
                   subnet_addressing_allowed = nil)
      @termination_id = termination_id
      @subnet_addressing_allowed = subnet_addressing_allowed
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      termination_id = hash['terminationId']
      subnet_addressing_allowed = hash['subnetAddressingAllowed']

      # Create object from extracted values.
      RogerTerminationConfigurationPayload.new(termination_id,
                                               subnet_addressing_allowed)
    end

    def self.from_element(root)
      termination_id = XmlUtilities.from_element(root, 'TerminationId', Integer)
      subnet_addressing_allowed = XmlUtilities.from_element(
        root, 'SubnetAddressingAllowed', TrueClass
      )

      new(termination_id,
          subnet_addressing_allowed)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'TerminationId', termination_id)
      XmlUtilities.add_as_subelement(doc, root, 'SubnetAddressingAllowed',
                                     subnet_addressing_allowed)

      root
    end
  end
end
