# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ScopeEnum.
  class ScopeEnum
    SCOPE_ENUM = [
      # TODO: Write general description for SYSTEM
      SYSTEM = 'SYSTEM'.freeze,

      # TODO: Write general description for ALL
      ALL = 'ALL'.freeze,

      # TODO: Write general description for ACCOUNT_ADMIN
      ACCOUNT_ADMIN = 'ACCOUNT_ADMIN'.freeze,

      # TODO: Write general description for ACCOUNT
      ACCOUNT = 'ACCOUNT'.freeze
    ].freeze
  end
end
