# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # ServiceType.
  class ServiceTypeEnum
    SERVICE_TYPE_ENUM = [
      # TODO: Write general description for HTTPV1
      HTTPV1 = 'HTTPV1'.freeze,

      # TODO: Write general description for HTTPV2
      HTTPV2 = 'HTTPV2'.freeze
    ].freeze
  end
end
