# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # SipPeers Model.
  class SipPeers < BaseModel
    # TODO: Write general description for this method
    # @return [List of SipPeer]
    attr_accessor :sip_peers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sip_peers'] = 'sipPeers'
      @_hash
    end

    def initialize(sip_peers = nil)
      @sip_peers = sip_peers
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      sip_peers = nil
      unless hash['sipPeers'].nil?
        sip_peers = []
        hash['sipPeers'].each do |structure|
          sip_peers << (SipPeer.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SipPeers.new(sip_peers)
    end

    def self.from_element(root)
      sip_peers = XmlUtilities.from_element_to_array(root, 'SipPeer', SipPeer)

      new(sip_peers)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'SipPeer', sip_peers)

      root
    end
  end
end
