# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # SipPeerTelephoneNumbers Model.
  class SipPeerTelephoneNumbers < BaseModel
    # TODO: Write general description for this method
    # @return [List of SipPeerTelephoneNumber]
    attr_accessor :sip_peer_telephone_numbers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sip_peer_telephone_numbers'] = 'sipPeerTelephoneNumbers'
      @_hash
    end

    def initialize(sip_peer_telephone_numbers = nil)
      @sip_peer_telephone_numbers = sip_peer_telephone_numbers
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      sip_peer_telephone_numbers = nil
      unless hash['sipPeerTelephoneNumbers'].nil?
        sip_peer_telephone_numbers = []
        hash['sipPeerTelephoneNumbers'].each do |structure|
          sip_peer_telephone_numbers << (SipPeerTelephoneNumber.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SipPeerTelephoneNumbers.new(sip_peer_telephone_numbers)
    end

    def self.from_element(root)
      sip_peer_telephone_numbers = XmlUtilities.from_element_to_array(
        root, 'SipPeerTelephoneNumber', SipPeerTelephoneNumber
      )

      new(sip_peer_telephone_numbers)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'SipPeerTelephoneNumber',
                                           sip_peer_telephone_numbers)

      root
    end
  end
end
