# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # SipPeerHttpSettings Model.
  class SipPeerHttpSettings < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :application_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['application_id'] = 'applicationId'
      @_hash
    end

    def initialize(application_id = nil)
      @application_id = application_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      application_id = hash['applicationId']

      # Create object from extracted values.
      SipPeerHttpSettings.new(application_id)
    end

    def self.from_element(root)
      application_id = XmlUtilities.from_element(root, 'HttpVoiceV2AppId',
                                                 String)

      new(application_id)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'HttpVoiceV2AppId',
                                     application_id)

      root
    end
  end
end
