# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # SiteBillingId Model.
  class SiteBillingId < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :billing_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['billing_id'] = 'billingId'
      @_hash
    end

    def initialize(billing_id = nil)
      @billing_id = billing_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      billing_id = hash['billingId']

      # Create object from extracted values.
      SiteBillingId.new(billing_id)
    end

    def self.from_element(root)
      billing_id = XmlUtilities.from_element(root, 'IdValue', String)

      new(billing_id)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'IdValue', billing_id)

      root
    end
  end
end
