# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Status3.
  class Status3Enum
    STATUS3_ENUM = [
      # TODO: Write general description for RECEIVED
      RECEIVED = 'RECEIVED'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'PROCESSING'.freeze,

      # TODO: Write general description for ACTION_REQUIRED
      ACTION_REQUIRED = 'ACTION_REQUIRED'.freeze,

      # TODO: Write general description for COMPLETE
      COMPLETE = 'COMPLETE'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for REQUESTED_CANCEL
      REQUESTED_CANCEL = 'REQUESTED_CANCEL'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze
    ].freeze
  end
end
