# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Status Model.
  class Status < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['description'] = 'description'
      @_hash['code'] = 'code'
      @_hash
    end

    def initialize(description = nil,
                   code = nil)
      @description = description
      @code = code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      description = hash['description']
      code = hash['code']

      # Create object from extracted values.
      Status.new(description,
                 code)
    end

    def self.from_element(root)
      description = XmlUtilities.from_element(root, 'Description', String)
      code = XmlUtilities.from_element(root, 'Code', Integer)

      new(description,
          code)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Description', description)
      XmlUtilities.add_as_subelement(doc, root, 'Code', code)

      root
    end
  end
end
