# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TelephoneNumberGroupError Model.
  class TelephoneNumberGroupError < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :telephone_numbers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['description'] = 'description'
      @_hash['telephone_numbers'] = 'telephoneNumbers'
      @_hash
    end

    def initialize(code = nil,
                   description = nil,
                   telephone_numbers = nil)
      @code = code
      @description = description
      @telephone_numbers = telephone_numbers
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash['code']
      description = hash['description']
      telephone_numbers = hash['telephoneNumbers']

      # Create object from extracted values.
      TelephoneNumberGroupError.new(code,
                                    description,
                                    telephone_numbers)
    end

    def self.from_element(root)
      code = XmlUtilities.from_element(root, 'Code', Integer)
      description = XmlUtilities.from_element(root, 'Description', String)
      telephone_numbers = XmlUtilities.from_element_to_array(
        root, 'TelephoneNumber', String,
        wrapping_element_name: 'TelephoneNumbers'
      )

      new(code,
          description,
          telephone_numbers)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'Code', code)
      XmlUtilities.add_as_subelement(doc, root, 'Description', description)
      XmlUtilities.add_array_as_subelement(
        doc, root, 'TelephoneNumber', telephone_numbers,
        wrapping_element_name: 'TelephoneNumbers'
      )

      root
    end
  end
end
