# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TelephoneNumberAvailableNnRoutes Model.
  class TelephoneNumberAvailableNnRoutes < BaseModel
    # TODO: Write general description for this method
    # @return [List of TnDetailsNnRoute]
    attr_accessor :tn_details_nn_routes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tn_details_nn_routes'] = 'tnDetailsNnRoutes'
      @_hash
    end

    def initialize(tn_details_nn_routes = nil)
      @tn_details_nn_routes = tn_details_nn_routes
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      tn_details_nn_routes = nil
      unless hash['tnDetailsNnRoutes'].nil?
        tn_details_nn_routes = []
        hash['tnDetailsNnRoutes'].each do |structure|
          tn_details_nn_routes << (TnDetailsNnRoute.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      TelephoneNumberAvailableNnRoutes.new(tn_details_nn_routes)
    end

    def self.from_element(root)
      tn_details_nn_routes = XmlUtilities.from_element_to_array(
        root, 'NNRoute', TnDetailsNnRoute
      )

      new(tn_details_nn_routes)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(doc, root, 'NNRoute',
                                           tn_details_nn_routes)

      root
    end
  end
end
