# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TelephoneNumbers Model.
  class TelephoneNumbers < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :tns_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tns_list'] = 'tnsList'
      @_hash
    end

    def initialize(tns_list = nil)
      @tns_list = tns_list
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      tns_list = hash['tnsList']

      # Create object from extracted values.
      TelephoneNumbers.new(tns_list)
    end

    def self.from_element(root)
      tns_list = XmlUtilities.from_element_to_array(
        root, 'TelephoneNumber', String,
        wrapping_element_name: 'TelephoneNumberList'
      )

      new(tns_list)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_array_as_subelement(
        doc, root, 'TelephoneNumber', tns_list,
        wrapping_element_name: 'TelephoneNumberList'
      )

      root
    end
  end
end
