# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TnMessagingType.
  class TnMessagingTypeEnum
    TN_MESSAGING_TYPE_ENUM = [
      # TODO: Write general description for ON_NET_TNS
      ON_NET_TNS = 'ON_NET_TNS'.freeze,

      # TODO: Write general description for OFF_NET_TNS
      OFF_NET_TNS = 'OFF_NET_TNS'.freeze,

      # TODO: Write general description for OFF_NET_CA_TNS
      OFF_NET_CA_TNS = 'OFF_NET_CA_TNS'.freeze,

      # TODO: Write general description for EXTERNAL_CUSTOMER_OWNED_TNS
      EXTERNAL_CUSTOMER_OWNED_TNS = 'EXTERNAL_CUSTOMER_OWNED_TNS'.freeze,

      # TODO: Write general description for EXTERNAL_THIRD_PARTY_TNS
      EXTERNAL_THIRD_PARTY_TNS = 'EXTERNAL_THIRD_PARTY_TNS'.freeze,

      # TODO: Write general description for EXTERNAL_CANADIAN_TNS
      EXTERNAL_CANADIAN_TNS = 'EXTERNAL_CANADIAN_TNS'.freeze,

      # TODO: Write general description for TOLL_FREE_TNS
      TOLL_FREE_TNS = 'TOLL_FREE_TNS'.freeze,

      # TODO: Write general description for EXTERNAL_TOLL_FREE_TNS
      EXTERNAL_TOLL_FREE_TNS = 'EXTERNAL_TOLL_FREE_TNS'.freeze,

      # TODO: Write general description for A2P_ON_NET_TNS
      A2P_ON_NET_TNS = 'A2P_ON_NET_TNS'.freeze,

      # TODO: Write general description for A2P_OFF_NET_TNS
      A2P_OFF_NET_TNS = 'A2P_OFF_NET_TNS'.freeze,

      # TODO: Write general description for INCORRECT_VALUE
      INCORRECT_VALUE = 'INCORRECT_VALUE'.freeze
    ].freeze
  end
end
