# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TnOptionOrderWarningPayload Model.
  class TnOptionOrderWarningPayload < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :telephone_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['telephone_number'] = 'telephoneNumber'
      @_hash['description'] = 'description'
      @_hash
    end

    def initialize(telephone_number = nil,
                   description = nil)
      @telephone_number = telephone_number
      @description = description
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      telephone_number = hash['telephoneNumber']
      description = hash['description']

      # Create object from extracted values.
      TnOptionOrderWarningPayload.new(telephone_number,
                                      description)
    end

    def self.from_element(root)
      telephone_number = XmlUtilities.from_element(root, 'TelephoneNumber',
                                                   String)
      description = XmlUtilities.from_element(root, 'Description', String)

      new(telephone_number,
          description)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'TelephoneNumber',
                                     telephone_number)
      XmlUtilities.add_as_subelement(doc, root, 'Description', description)

      root
    end
  end
end
