# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TokenScope Model.
  class TokenScope < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :account_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_id'] = 'accountId'
      @_hash
    end

    def initialize(account_id = nil)
      @account_id = account_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_id = hash['accountId']

      # Create object from extracted values.
      TokenScope.new(account_id)
    end

    def self.from_element(root)
      account_id = XmlUtilities.from_element(root, 'AccountScope', Integer)

      new(account_id)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'AccountScope', account_id)

      root
    end
  end
end
