# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # TollFreeVanitySearchAndOrderType Model.
  class TollFreeVanitySearchAndOrderType < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :vanity

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['vanity'] = 'vanity'
      @_hash['quantity'] = 'quantity'
      @_hash
    end

    def initialize(vanity = nil,
                   quantity = nil)
      @vanity = vanity
      @quantity = quantity
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      vanity = hash['vanity']
      quantity = hash['quantity']

      # Create object from extracted values.
      TollFreeVanitySearchAndOrderType.new(vanity,
                                           quantity)
    end

    def self.from_element(root)
      vanity = XmlUtilities.from_element(root, 'TollFreeVanity', String)
      quantity = XmlUtilities.from_element(root, 'Quantity', Integer)

      new(vanity,
          quantity)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'TollFreeVanity', vanity)
      XmlUtilities.add_as_subelement(doc, root, 'Quantity', quantity)

      root
    end
  end
end
