# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # UcTrunkingCloudConfigurationPayload Model.
  class UcTrunkingCloudConfigurationPayload < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :trunks

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['trunks'] = 'trunks'
      @_hash
    end

    def initialize(trunks = nil)
      @trunks = trunks
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      trunks = hash['trunks']

      # Create object from extracted values.
      UcTrunkingCloudConfigurationPayload.new(trunks)
    end

    def self.from_element(root)
      trunks = XmlUtilities.from_element(root, 'BiDirectionalTrunks', String)

      new(trunks)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'BiDirectionalTrunks', trunks)

      root
    end
  end
end
