# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # UseType.
  class UseTypeEnum
    USE_TYPE_ENUM = [
      # TODO: Write general description for BUSINESS
      BUSINESS = 'BUSINESS'.freeze,

      # TODO: Write general description for RESIDENTIAL
      RESIDENTIAL = 'RESIDENTIAL'.freeze
    ].freeze
  end
end
