# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # BandwidthMessageItem Model.
  class BandwidthMessageItem < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :source_tn

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :destination_tn

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message_direction

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :segment_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :error_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :receive_time

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['message_id'] = 'messageId'
      @_hash['account_id'] = 'accountId'
      @_hash['source_tn'] = 'sourceTn'
      @_hash['destination_tn'] = 'destinationTn'
      @_hash['message_status'] = 'messageStatus'
      @_hash['message_direction'] = 'messageDirection'
      @_hash['message_type'] = 'messageType'
      @_hash['segment_count'] = 'segmentCount'
      @_hash['error_code'] = 'errorCode'
      @_hash['receive_time'] = 'receiveTime'
      @_hash['carrier_name'] = 'carrierName'
      @_hash
    end

    def initialize(message_id = nil,
                   account_id = nil,
                   source_tn = nil,
                   destination_tn = nil,
                   message_status = nil,
                   message_direction = nil,
                   message_type = nil,
                   segment_count = nil,
                   error_code = nil,
                   receive_time = nil,
                   carrier_name = nil)
      @message_id = message_id
      @account_id = account_id
      @source_tn = source_tn
      @destination_tn = destination_tn
      @message_status = message_status
      @message_direction = message_direction
      @message_type = message_type
      @segment_count = segment_count
      @error_code = error_code
      @receive_time = receive_time
      @carrier_name = carrier_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      message_id = hash['messageId']
      account_id = hash['accountId']
      source_tn = hash['sourceTn']
      destination_tn = hash['destinationTn']
      message_status = hash['messageStatus']
      message_direction = hash['messageDirection']
      message_type = hash['messageType']
      segment_count = hash['segmentCount']
      error_code = hash['errorCode']
      receive_time = hash['receiveTime']
      carrier_name = hash['carrierName']

      # Create object from extracted values.
      BandwidthMessageItem.new(message_id,
                               account_id,
                               source_tn,
                               destination_tn,
                               message_status,
                               message_direction,
                               message_type,
                               segment_count,
                               error_code,
                               receive_time,
                               carrier_name)
    end
  end
end
